services:
  bot:
    build: .
    volumes:
      - ./data/bot/config:/app/config
      - ./data/bot/plugins:/app/plugins
      - ./data/bot/servers:/app/servers
      - ./data/bot/template:/app/template
  database:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
  velocity:
    image: itzg/mc-proxy:latest
    tty: true
    environment:
      EULA: "TRUE"
      TYPE: VELOCITY
      JVM_DD_OPTS: javalin.port=30000
    volumes:
      - ./data/velocity/config:/config
      - ./data/velocity/plugins:/plugins
  lobby:
    image: itzg/minecraft-server:latest
    stdin_open: true
    tty: true
    environment:
      VERSION: 1.21
      TYPE: PAPER
      MEMORY: 2G
    volumes:
      - ./data/lobby:/data
